[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ujson_manager"
version = "1.0.3"
requires-python = ">= 3.8"
license = {file = "LICENSE"}
readme = "README.md"
authors = [
    {name = "unixtux"}
]
dependencies = [
    "aiotgm"
]

[project.urls]
Repository = "https://github.com/unixtux/ujson_manager"

[tool.setuptools]
packages = ["ujson_manager"]
