[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ujson_manager"
version = "1.0.1"
requires-python = ">= 3.8"
license = {file = "LICENSE"}
authors = [
    {name = "unixtux"}
]
dependencies = [
    "aiotgm"
]

[tool.setuptools]
packages = ["ujson_manager"]
